### PR TITLE
Toscalix crypto algorithms

### PR DESCRIPTION
**Pull request by toscalix**
* Restructuring of the folders
* Improvements on the definitions template
* Adaptation of the definitions to the new template
* Creation of documents for specs and project
* README adapted

### CODE REVIEW

**Comment by toscalix** [comment]
Other relevant changes:
* Added the definitions index file, which is new.
* Folder for slide decks and diagrams. Added the slide deck from the openchain webinar

**Comment by toscalix** [comment]
Comments from @eeisegn 

I would propose the following:
```
section1 -> definition
section2 -> implementations
section3 -> references
``` 
General consensus, this a good step. Can we do it in a coming iteration?

**Comment by toscalix** [comment]
From @juliancoccia 
if this is the case, All we have to do is string replace in all definitions and change section3 with references in these two lines in the script
```
                    if 'section3' in data and 'keywords' in data['section3']:
                        for keyword in data['section3']['keywords']:
```

**Comment by toscalix** [comment]
Other relevant conversation on chat...
@eeisegn 
I want to eventually add regex as an option for identifying an algorithm. for now it's just keywords

@juliancoccia 
that's good for the future, but this already solves a big problem

**Review by eeisegn — APPROVED** [review]
Needs further refinement for yaml field naming

**Pull request merged**
